version: '3.8'

services:
  # Web app
  web:
    image: ghcr.io/amtteamheig/amt_project:latest
    container_name: 'help2000_webapp_container'
    ports:
      - "9080:9080"
    depends_on:
      - db
    expose:
      - '9080'

  # Database
  db:
    image: library/mysql:8.0.21
    restart: always
    container_name: 'help2000_db_container'
    environment:
      MYSQL_DATABASE: 'help2000'
      # User so we don't have to use root
      MYSQL_USER: 'dbDevHelp2000'
      MYSQL_PASSWORD: 'devpass'
      MYSQL_ROOT_PASSWORD: 'devpa$$'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
    volumes:
      - ./docker/database/:/docker-entrypoint-initdb.d/
