version: '3.8'

services:
  # Web app
  web:
    image: ghcr.io/amtteamheig/amt_project:latest
    container_name: 'help2000_webapp_container'
    networks:
      - help2000
    ports:
      - "9080:9080"
    depends_on:
      - db
    expose:
      - '9080'
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9080" ]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s


  # Database
  db:
    image: library/mysql:8.0.21
    restart: always
    container_name: 'help2000_db_container'
    environment:
      MYSQL_DATABASE: 'help2000'
      # User so we don't have to use root
      MYSQL_USER: 'dbDevHelp2000'
      MYSQL_PASSWORD: 'devpass'
      MYSQL_ROOT_PASSWORD: 'devpa$$'
    networks:
      - help2000
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3307:3306'
    expose:
      # Opens port 3307 on the container
      - '3306'
    volumes:
      - ./docker/database/:/docker-entrypoint-initdb.d/
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

networks:
  help2000:
    name: "amt"
    driver: "bridge"