version: '3.8'

services:
  # Web app
  web:
    image: amt_project:local
    build:
      context: .
      dockerfile: Dockerfile

  # Database
  db:
    image: library/mysql:8.0.21

  codecpetjs:
    container_name: "help2000_codeceptjs"
    image: codeception/codeceptjs
    depends_on:
      - web
    network_mode: "host"
    volumes:
      - ./e2e:/tests

