-- MySQL Script generated by MySQL Workbench
-- Fri Oct 23 17:34:44 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema help2000
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema help2000
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `help2000` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `help2000` ;

-- -----------------------------------------------------
-- Table `help2000`.`tblUser`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `help2000`.`tblUser` (
  `id` VARCHAR(256) NOT NULL,
  `userName` VARCHAR(512) NOT NULL,
  `email` VARCHAR(512) NOT NULL,
  `encryptedPassword` VARCHAR(512) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `userName_UNIQUE` (`userName` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `help2000`.`tblQuestion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `help2000`.`tblQuestion` (
  `id` VARCHAR(256) NOT NULL,
  `title` VARCHAR(512) NOT NULL,
  `description` LONGTEXT NOT NULL,
  `creationDate` DATETIME NOT NULL,
  `tblUser_id` VARCHAR(256) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tblQuestion_tblUser_idx` (`tblUser_id` ASC) VISIBLE,
  CONSTRAINT `fk_tblQuestion_tblUser`
    FOREIGN KEY (`tblUser_id`)
    REFERENCES `help2000`.`tblUser` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `help2000`.`tblAnswer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `help2000`.`tblAnswer` (
  `id` VARCHAR(256) NOT NULL,
  `description` LONGTEXT NOT NULL,
  `creationDate` DATETIME NOT NULL,
  `tblQuestion_id` VARCHAR(256) NOT NULL,
  `tblUser_id` VARCHAR(256) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tblAnswer_tblQuestion1_idx` (`tblQuestion_id` ASC) VISIBLE,
  INDEX `fk_tblAnswer_tblUser1_idx` (`tblUser_id` ASC) VISIBLE,
  CONSTRAINT `fk_tblAnswer_tblQuestion1`
    FOREIGN KEY (`tblQuestion_id`)
    REFERENCES `help2000`.`tblQuestion` (`id`)
    ON DELETE CASCADE
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_tblAnswer_tblUser1`
    FOREIGN KEY (`tblUser_id`)
    REFERENCES `help2000`.`tblUser` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `help2000`.`tblComment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `help2000`.`tblComment` (
  `id` VARCHAR(256) NOT NULL,
  `description` LONGTEXT NOT NULL,
  `creationDate` DATETIME NOT NULL,
  `tblAnswer_id` VARCHAR(256) NULL DEFAULT NULL,
  `tblQuestion_id` VARCHAR(256) NULL DEFAULT NULL,
  `tblUser_id` VARCHAR(256) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tblComment_tblAnswer1_idx` (`tblAnswer_id` ASC) VISIBLE,
  INDEX `fk_tblComment_tblQuestion1_idx` (`tblQuestion_id` ASC) VISIBLE,
  INDEX `fk_tblComment_tblUser1_idx` (`tblUser_id` ASC) VISIBLE,
  CONSTRAINT `fk_tblComment_tblAnswer1`
    FOREIGN KEY (`tblAnswer_id`)
    REFERENCES `help2000`.`tblAnswer` (`id`)
    ON DELETE CASCADE
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_tblComment_tblQuestion1`
    FOREIGN KEY (`tblQuestion_id`)
    REFERENCES `help2000`.`tblQuestion` (`id`)
    ON DELETE CASCADE
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_tblComment_tblUser1`
    FOREIGN KEY (`tblUser_id`)
    REFERENCES `help2000`.`tblUser` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `help2000`.`tblTag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `help2000`.`tblTag` (
  `id` VARCHAR(256) NOT NULL,
  `name` VARCHAR(256) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `help2000`.`tblTag_has_tblQuestion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `help2000`.`tblTag_has_tblQuestion` (
  `tblTag_id` VARCHAR(256) NOT NULL,
  `tblQuestion_id` VARCHAR(256) NOT NULL,
  PRIMARY KEY (`tblTag_id`, `tblQuestion_id`),
  INDEX `fk_tblTag_has_tblQuestion_tblQuestion1_idx` (`tblQuestion_id` ASC) VISIBLE,
  INDEX `fk_tblTag_has_tblQuestion_tblTag1_idx` (`tblTag_id` ASC) VISIBLE,
  CONSTRAINT `fk_tblTag_has_tblQuestion_tblQuestion1`
    FOREIGN KEY (`tblQuestion_id`)
    REFERENCES `help2000`.`tblQuestion` (`id`),
  CONSTRAINT `fk_tblTag_has_tblQuestion_tblTag1`
    FOREIGN KEY (`tblTag_id`)
    REFERENCES `help2000`.`tblTag` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `help2000`.`tblUser_vote_tblComment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `help2000`.`tblUser_vote_tblAnswer` (
  `tblUser_id` VARCHAR(256) NOT NULL,
  `tblAnswer_id` VARCHAR(256) NOT NULL,
  `positv` TINYINT NOT NULL,
  PRIMARY KEY (`tblUser_id`, `tblAnswer_id`))
  /*INDEX `fk_tblUser_has_tblComment_tblComment1_idx` (`tblComment_id` ASC) VISIBLE,
  INDEX `fk_tblUser_has_tblComment_tblUser1_idx` (`tblUser_id` ASC) VISIBLE,
  CONSTRAINT `fk_tblUser_has_tblComment_tblUser1`
    FOREIGN KEY (`tblUser_id`)
    REFERENCES `help2000`.`tblUser` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tblUser_has_tblComment_tblComment1`
    FOREIGN KEY (`tblComment_id`)
    REFERENCES `help2000`.`tblComment` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)*/
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `help2000`.`tblUser_vote_tblQuestion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `help2000`.`tblUser_vote_tblQuestion` (
  `tblUser_id` VARCHAR(256) NOT NULL,
  `tblQuestion_id` VARCHAR(256) NOT NULL,
  `positiv` TINYINT NOT NULL,
  PRIMARY KEY (`tblUser_id`, `tblQuestion_id`))
  /*INDEX `fk_tblUser_has_tblQuestion_tblQuestion1_idx` (`tblQuestion_id` ASC) VISIBLE,
  INDEX `fk_tblUser_has_tblQuestion_tblUser1_idx` (`tblUser_id` ASC) VISIBLE,
  CONSTRAINTS FAILS FOR SOME REASONS, WORKS IN TERMINAL ON MYSQL...*/
  /*CONSTRAINT `fk_tblUser_has_tblQuestion_tblUser1`
    FOREIGN KEY (`tblUser_id`)
    REFERENCES `help2000`.`tblUser` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tblUser_has_tblQuestion_tblQuestion1`
    FOREIGN KEY (`tblQuestion_id`)
    REFERENCES `help2000`.`tblQuestion` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)*/
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
