-- MySQL Script generated by MySQL Workbench
-- ven 02 oct 2020 10:18:10
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema help2000
-- -----------------------------------------------------
DROP DATABASE IF EXISTS `help2000`
CREATE SCHEMA IF NOT EXISTS `help2000` ;
USE `help2000` ;

-- -----------------------------------------------------
-- Table `help2000`.`tblUser`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `help2000`.`tblUser` (
  `id` INT NOT NULL,
  `userName` VARCHAR(512) NOT NULL,
  `email` VARCHAR(512) NOT NULL,
  `encryptedPassword` VARCHAR(512) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `userName_UNIQUE` (`userName` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `help2000`.`tblQuestion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `help2000`.`tblQuestion` (
  `id` INT NOT NULL,
  `title` VARCHAR(512) NOT NULL,
  `description` LONGTEXT NOT NULL,
  `vote` INT NOT NULL,
  `creationDate` DATETIME NOT NULL,
  `tblUser_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tblQuestion_tblUser_idx` (`tblUser_id` ASC) VISIBLE,
  CONSTRAINT `fk_tblQuestion_tblUser`
    FOREIGN KEY (`tblUser_id`)
    REFERENCES `help2000`.`tblUser` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `help2000`.`tblTag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `help2000`.`tblTag` (
  `id` INT NOT NULL,
  `name` VARCHAR(256) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `help2000`.`tblAnswer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `help2000`.`tblAnswer` (
  `id` INT NOT NULL,
  `description` LONGTEXT NOT NULL,
  `vote` INT NOT NULL,
  `creationDate` DATETIME NOT NULL,
  `tblQuestion_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tblAnswer_tblQuestion1_idx` (`tblQuestion_id` ASC) VISIBLE,
  CONSTRAINT `fk_tblAnswer_tblQuestion1`
    FOREIGN KEY (`tblQuestion_id`)
    REFERENCES `help2000`.`tblQuestion` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `help2000`.`tblComment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `help2000`.`tblComment` (
  `id` INT NOT NULL,
  `description` LONGTEXT NOT NULL,
  `vote` INT NOT NULL,
  `creationDate` DATETIME NOT NULL,
  `tblAnswer_id` INT NULL,
  `tblQuestion_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tblComment_tblAnswer1_idx` (`tblAnswer_id` ASC) VISIBLE,
  INDEX `fk_tblComment_tblQuestion1_idx` (`tblQuestion_id` ASC) VISIBLE,
  CONSTRAINT `fk_tblComment_tblAnswer1`
    FOREIGN KEY (`tblAnswer_id`)
    REFERENCES `help2000`.`tblAnswer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tblComment_tblQuestion1`
    FOREIGN KEY (`tblQuestion_id`)
    REFERENCES `help2000`.`tblQuestion` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `help2000`.`tblTag_has_tblQuestion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `help2000`.`tblTag_has_tblQuestion` (
  `tblTag_id` INT NOT NULL,
  `tblQuestion_id` INT NOT NULL,
  PRIMARY KEY (`tblTag_id`, `tblQuestion_id`),
  INDEX `fk_tblTag_has_tblQuestion_tblQuestion1_idx` (`tblQuestion_id` ASC) VISIBLE,
  INDEX `fk_tblTag_has_tblQuestion_tblTag1_idx` (`tblTag_id` ASC) VISIBLE,
  CONSTRAINT `fk_tblTag_has_tblQuestion_tblTag1`
    FOREIGN KEY (`tblTag_id`)
    REFERENCES `help2000`.`tblTag` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tblTag_has_tblQuestion_tblQuestion1`
    FOREIGN KEY (`tblQuestion_id`)
    REFERENCES `help2000`.`tblQuestion` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
