name: Build and publish Docker Image for the Help 2000 Website

on:
  push:
    branches:
      - master

jobs:
  docker-image:
    runs-on: ubuntu-latest
    name: Create a docker container

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Setup JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      # Maven package
      - name: Build with Maven
        run: mvn clean package -Dmaven.test.skip=true

      # Docker build (with PAT)
      - name: Build Docker image (with mvn clean package)
        run: |
          echo ${{ secrets.HELP2000_PAT }} | docker login ghcr.io -u dev-help2000 --password-stdin
          docker build -t amt-project/help2000 .
          docker tag amt-project/help2000 ghcr.io/amtteamheig/amt_project
          docker push ghcr.io/amtteamheig/amt_project