# This is a basic workflow to help you get started with Actions

name: Build and publish Docker Image for the Help 2000 Website

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Setup environment with Java
      - name: Setup JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      
      # Cache optimization
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
            
      # Maven package
      - name: Build with Maven
        run: mvn clean package

      # Docker build (with secret)
      - name: Build Docker image (with mvn clean package)
        run: |
          echo ${{ secrets.HELP2000_PAT }} | sudo docker login ghcr.io -u dev-help2000 --password-stdin
          sudo docker build -t amt-project/help2000 .
          sudo ./build-image
          sudo docker tag amt-project/help2000 ghcr.io/amtteam01/amt_project
          sudo docker push ghcr.io/amtteam01/amt_project
